### ISSUE TITLE
Documentation for endpoints?

### ISSUE THREAD

**Issue by kenhkan** [haskell-servant/servant-docs#10]
I know that servant-docs has an [Endpoint](http://hackage.haskell.org/package/servant-docs-0.3/docs/Servant-Docs.html#t:Endpoint) type but it appears that there is no way of documenting it. Is this a planned feature or have I missed something in the doc or source? Thanks for any insight.

p.s. Just discovered servant via Halcyon and I absolutely love the servant philosophy, especially the docs part!

**Comment by christian-marie** [comment]
Not easily, no. The Endpoint type is more of an internal part of the "AST" of an API.

It's certainly something I'm interested in adding support for, the issue is how to provide an interface to the user that makes sense.

This was recently added:

```haskell
-- | Generate the docs for a given API that implements 'HasDocs' with with any
-- number of introduction(s)
docsWithIntros :: HasDocs layout => [DocIntro] -> Proxy layout -> API
docsWithIntros intros p = docs p & apiIntros <>~ intros
```

So perhaps that makes sense, and with a type family and a helper function such an interface could be made "safe" for an endpoint (i.e. you could not document an endpoint that does not exist).

That's a little awkward, though.

Another option may be that we somehow require a constraint for HasDocs on each "branch" of an API, via some kind of type magic, such that in an API:

```haskell

type API = "a" :> Get () :<|> "b" :> Put ()

-- Has a sane default
instance HasDocs "a" :> Get ()

instance HasDocs "b" :> Get () where
  simplerHelper _ = [SomeType "some extra docs" ["with titles and multiple sections, mos likely"]]
```

Thoughts?

**Comment by christian-marie** [comment]
In the meantime, you can add extra sections to an endpoint via Note if you have a custom type in there somewhere you want to document.

**Comment by alpmestan** [comment]
@kenhkan well the goal was to have everything about each endpoint be generated automatically. I'm not sure how we could add what you want, i.e just targetting a particular endpoint with some comments, without cluttering everything -- @christian-marie's suggestion would force us to write an instance per endpoint for example

**Comment by christian-marie** [comment]
This could be an extra constraint, such as WellDocumented, that's only a constraint on a "betterDocs" function.

My first suggestion requires no such instance, it seems clumsy though.

**Comment by christian-marie** [comment]
I'm leaning towards the first option, if this needed to be done. "Distributing" a constraint for every "endpoint" in a type is a little tricky.

**Comment by kenhkan** [comment]
@alpmestan servant-docs as it stands suffices my needs actually. It's just that when I was getting it to work I realized that there could be a need to annotate an endpoint because of certain peculiarities. Say, if an endpoint has two versions (e.g. `POST /add-user/v1/` and `POST /add-user/v2/`) because of the need to support legacy clients, the parameters may be the same but the effect on the system may differ (e.g. `v1` would only add the user in the running app's database, but `v2` would do that as well as add the user to the company's internal CardDAV server).

@christian-marie I think the Note idea would cover most cases. So I'm a happy man! :) On the two suggestions, wouldn't the first only cover the entire API, not individual endpoints? Your second suggestion was actually what I had in mind as I opened the issue as well.

**Comment by christian-marie** [comment]
That is what I meant ^^

We can clean it up further and improve such a solution if it seems reasonable.

**Comment by christian-marie** [comment]
Any thoughts on the PR?

**Comment by alpmestan** [comment]
Can we consider this issue solved, given that the general info API PR has been merged?

**Comment by christian-marie** [comment]
I do. @kenhkan Does this work for you?

**Comment by kenhkan** [comment]
Ah. Sorry. Somehow GitHub stopped sending me notifications. Yes. I'm closing this. Thanks for the ideas guys!
