### ISSUE TITLE
It is weird that Control.Lens and Data.Monoid is re-exported

### ISSUE THREAD

**Issue by christian-marie** [haskell-servant/servant-docs#14]
This was counter-intuitive for several of us. Forcing a full Control.Lens import onto your users is pretty odd.

I propose removing the re-export before major release.

**Comment by alpmestan** [comment]
This was for convenience mostly -- when you're doing anything non-trivial with servant-docs, you need those imports anyway. I don't mind nuking them from the export list though if it annoys users of the package.

**Comment by alpmestan** [comment]
Fixed in 38fea6060e97e7f219fbd2b235c7132ff1d57684.
