### ISSUE TITLE
API Blueprint

### ISSUE THREAD

**Issue by AndrewRademacher** [haskell-servant/servant-docs#17]
Has there been any consideration for writing servant docs output in API Blueprint format 1A?

**Comment by jkarni** [comment]
There's been some talk of outputting compatible formats (to API Blueprint, Swagger, etc.) but as far as I know no one has really started work on it...

**Comment by alpmestan** [comment]
Consideration, yes, definitely! Anything that can help integrate servant with existing tooling is appreciated. We however haven't started working on that. Would you be interested in working on that? We would definitely be around to help, if needed.

**Comment by AndrewRademacher** [comment]
I would be interested in doing it, but I have some bandwidth issues to resolve first.

**Comment by jkarni** [comment]
This issue was moved to haskell-servant/servant#35
